const STAGES=["Settle","Learn","Copy","Recall","Use","Reflect"];
function fresh(){return{selected:1,stage:0,completed:{},stageDone:{},vocabDone:{},notes:{},confidence:{},skips:0}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return fresh()}}
let state=load(),timerId=null,timerLeft=180;
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1700)}
function lesson(){return COURSE.find(x=>x.day===state.selected)||COURSE[0]}
function firstOpen(){return COURSE.find(x=>!state.completed[x.day])||COURSE[COURSE.length-1]}
function effectiveDate(day){const d=new Date(START);d.setDate(d.getDate()+day-1+(state.skips||0));return d}
function fmt(d){return d.toLocaleDateString("en-AU",{weekday:"short",day:"numeric",month:"short",year:"numeric"})}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9 ]/g,"").trim().replace(/\s+/g,"-")}
function signLink(s){return "https://www.signbsl.com/sign/"+slug(s)}
function trustedLinks(l){let links=[["SignBSL dictionary","https://www.signbsl.com/"],["Signature learner support","https://www.signature.org.uk/students/learning-support/"]];if(l.title.toLowerCase().includes("finger"))links.unshift(["Fingerspelling guide","https://www.signature.org.uk/students/learning-support/fingerspelling/"]);return links.slice(0,3)}
function stageKey(day,stage){return day+"-"+stage}
function markStageDone(){state.stageDone[stageKey(state.selected,state.stage)]=true;save()}
function stageIsDone(day,stage){return !!state.stageDone[stageKey(day,stage)]}
function renderHome(){const n=firstOpen(),done=COURSE.filter(l=>state.completed[l.day]).length;document.getElementById("homePhase").textContent=n.phase;document.getElementById("homeTitle").textContent=n.title;document.getElementById("homeFocus").textContent=n.focus;document.getElementById("homeDay").textContent="Day "+n.day+" of 35";document.getElementById("homeDate").textContent=fmt(effectiveDate(n.day));document.getElementById("doneCount").textContent=done;document.getElementById("remainCount").textContent=35-done;document.getElementById("stageCount").textContent=Object.values(state.stageDone).filter(Boolean).length;const cs=Object.values(state.confidence).filter(Boolean);document.getElementById("confidenceText").textContent=cs.length?["","Needs work","Growing","Usable"][cs[cs.length-1]]:"—";document.getElementById("progressBar").style.width=Math.round(done/35*100)+"%";document.getElementById("journey").innerHTML=COURSE.map(l=>{const current=l.day===n.day&&!state.completed[l.day];return `<div class="day" data-day="${l.day}"><div class="dayNum">DAY ${l.day}</div><div><h4>${l.title}</h4><p>${l.phase} · ${l.focus}</p></div><span class="status ${state.completed[l.day]?"complete":current?"current":""}">${state.completed[l.day]?"Complete":current?"Next":"Open"}</span></div>`}).join("");document.querySelectorAll("[data-day]").forEach(el=>el.onclick=()=>openLesson(Number(el.dataset.day)))}
function openLesson(day){state.selected=day;state.stage=0;save();document.getElementById("home").classList.add("hidden");document.getElementById("session").classList.add("active");renderSession();window.scrollTo({top:0,behavior:"smooth"})}
function renderRail(){document.getElementById("stageRail").innerHTML=STAGES.map((s,i)=>`<div class="stageDot ${i===state.stage?"active":stageIsDone(state.selected,i)?"done":""}">${i+1} · ${s}</div>`).join("")}
function vocabCards(l){return l.vocab.map((v,i)=>{const done=state.vocabDone[l.day]?.[i];return `<div class="vocabCard ${done?"done":""}"><h4>${v}</h4><p>Open a video example. Watch twice before moving your hands. Then copy it slowly three times.</p><div class="resourceRow"><a class="resourceLink" href="${signLink(v)}" target="_blank" rel="noopener">Open video example ↗</a><button class="miniBtn ${done?"done":""}" data-vocab="${i}">${done?"Practised ✓":"Mark practised"}</button></div></div>`}).join("")}
function checklist(items,prefix){return `<div class="checklist">${items.map((x,i)=>`<label class="check"><input type="checkbox" data-check="${prefix}-${i}"><span>${x}</span></label>`).join("")}</div>`}
function renderStage(){const l=lesson(),i=state.stage,card=document.getElementById("stageCard");let body="";if(i===0)body=`<div class="stageLabel">Stage 1 of 6 · Settle</div><h3>Know exactly what you are doing today</h3><p class="lead">Today you are learning <strong>${l.focus.toLowerCase()}</strong>. You will watch, copy, retrieve and use the language before you finish.</p><div class="instruction"><strong>Do this now:</strong> Put your device where both hands and your face are visible. Remove audio distractions. Keep a mirror or camera nearby. Take one slow breath, then read the outcome below.</div><div class="prompt"><div><small>By the end of this session</small>${l.challenge}</div></div>${checklist(["My hands and face are visible","I have opened a mirror or camera","I understand today's final challenge"],"settle")}`;
if(i===1)body=`<div class="stageLabel">Stage 2 of 6 · Learn</div><h3>See each item before you try it</h3><p class="lead">Do not skim this stage. Open each example, watch it twice, then copy it slowly. Regional variation is normal, so choose one clear version and stay consistent today.</p><div class="resourceRow">${trustedLinks(l).map(x=>`<a class="resourceLink" href="${x[1]}" target="_blank" rel="noopener">${x[0]} ↗</a>`).join("")}</div><div class="vocabGrid">${vocabCards(l)}</div>`;
if(i===2)body=`<div class="stageLabel">Stage 3 of 6 · Copy</div><h3>Build the movement into your body</h3><p class="lead">Now practise deliberately. Accuracy first, smoothness second, speed last.</p><div class="instruction"><strong>Round 1:</strong> Copy each item three times while looking at the model.<br><strong>Round 2:</strong> Look away, produce it once, then check.<br><strong>Round 3:</strong> Record yourself producing the full set at a calm pace.</div>${checklist(l.steps.map((s,idx)=>`${idx+1}. ${s}`),"copy")}<div class="prompt"><div><small>Coach's cue</small>${l.coach}</div></div>`;
if(i===3)body=`<div class="stageLabel">Stage 4 of 6 · Recall</div><h3>Close the resource and retrieve</h3><p class="lead">This is where learning becomes usable. Do not reopen the video immediately when you hesitate. Give your memory five quiet seconds.</p><div class="prompt" id="recallPrompt"><div><small>Your prompt</small>${l.vocab[0]}</div></div><div class="resourceRow"><button class="btn" id="nextPrompt">Next prompt</button><button class="btn secondary" id="showList">Show full list</button></div><div id="fullList" style="display:none" class="instruction">${l.vocab.join(" · ")}</div><div class="instruction"><strong>Pass condition:</strong> Produce at least ${Math.max(3,Math.ceil(l.vocab.length*.7))} items without copying. Hesitation is allowed. Guessing wildly is not.</div>`;
if(i===4)body=`<div class="stageLabel">Stage 5 of 6 · Use</div><h3>Turn signs into communication</h3><p class="lead">Isolated signs are ingredients. This stage makes the meal.</p><div class="prompt"><div><small>Today's practical challenge</small>${l.challenge}</div></div><div class="instruction"><strong>Attempt 1:</strong> Do it slowly with notes.<br><strong>Attempt 2:</strong> Repeat with fewer notes and clearer facial expression.<br><strong>Attempt 3:</strong> Record one final version without voice. Watch it back once and identify one improvement.</div>${checklist(["I completed a first attempt","I repeated it with fewer prompts","I watched back one recording","My face and eye gaze supported the meaning"],"use")}`;
if(i===5)body=`<div class="stageLabel">Stage 6 of 6 · Reflect</div><h3>Close the loop</h3><p class="lead">${l.reflect}</p><textarea id="notes" placeholder="What can you now do? What needs a five-minute revisit?"></textarea><h4 style="margin:22px 0 8px">How usable does today's learning feel?</h4><div class="confidence"><button data-confidence="1">Needs another pass</button><button data-confidence="2">Growing</button><button data-confidence="3">Usable today</button></div><div class="instruction"><strong>Finish only when:</strong> you attempted the practical challenge, wrote one honest reflection, and chose a confidence level.</div>`;
body+=`<div class="stageNav"><div><button class="btn secondary" id="backStage" ${i===0?"disabled":""}>Previous</button></div><div>${i<5?`<button class="btn" id="nextStage">Complete stage and continue</button>`:`<button class="btn warn" id="skipLesson">Skip day and shift course</button><button class="btn good" id="finishLesson">Finish lesson</button>`}</div></div>`;card.innerHTML=body;
document.querySelectorAll("[data-vocab]").forEach(b=>b.onclick=()=>{state.vocabDone[l.day]=state.vocabDone[l.day]||{};state.vocabDone[l.day][b.dataset.vocab]=!state.vocabDone[l.day][b.dataset.vocab];save();renderStage()});
if(i===3){let idx=0;document.getElementById("nextPrompt").onclick=()=>{idx=(idx+1)%l.vocab.length;document.getElementById("recallPrompt").innerHTML=`<div><small>Your prompt</small>${l.vocab[idx]}</div>`};document.getElementById("showList").onclick=()=>{const f=document.getElementById("fullList");f.style.display=f.style.display==="none"?"block":"none"}}
if(i===5){document.getElementById("notes").value=state.notes[l.day]||"";document.getElementById("notes").oninput=e=>{state.notes[l.day]=e.target.value;save()};document.querySelectorAll("[data-confidence]").forEach(b=>{b.classList.toggle("active",Number(b.dataset.confidence)===state.confidence[l.day]);b.onclick=()=>{state.confidence[l.day]=Number(b.dataset.confidence);save();renderStage()}})}
document.getElementById("backStage").onclick=()=>{state.stage=Math.max(0,state.stage-1);save();renderSession();window.scrollTo({top:0,behavior:"smooth"})};
if(i<5)document.getElementById("nextStage").onclick=()=>{markStageDone();state.stage++;save();renderSession();window.scrollTo({top:0,behavior:"smooth"})};
if(i===5){document.getElementById("finishLesson").onclick=()=>{if(!(state.notes[l.day]||"").trim()||!state.confidence[l.day]){toast("Add a reflection and confidence check first");return}markStageDone();state.completed[l.day]=true;save();toast("Lesson complete");setTimeout(exitSession,500)};document.getElementById("skipLesson").onclick=()=>{state.skips=(state.skips||0)+1;save();toast("Course shifted forward by one day");exitSession()}}
}
function renderSession(){const l=lesson();document.getElementById("sessionPhase").textContent=l.phase+" · Day "+l.day+" of 35 · "+fmt(effectiveDate(l.day));document.getElementById("sessionTitle").textContent=l.title;document.getElementById("sessionFocus").textContent=l.focus;renderRail();renderStage()}
function exitSession(){document.getElementById("session").classList.remove("active");document.getElementById("home").classList.remove("hidden");state.selected=firstOpen().day;state.stage=0;save();renderHome();window.scrollTo({top:0,behavior:"smooth"})}
document.getElementById("beginBtn").onclick=()=>openLesson(firstOpen().day);document.getElementById("exitBtn").onclick=exitSession;document.getElementById("printBtn").onclick=()=>window.print();document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all saved progress on this device?")){localStorage.removeItem(KEY);state=fresh();renderHome();toast("Progress reset")}};
renderHome();
