const STAGES=["Orient","Retrieve","Learn","Practise","Use","Close"];
const RATINGS={0:"Needs another model",1:"Correct but hesitant",2:"Clear from memory"};
const $=id=>document.getElementById(id);
const esc=value=>String(value??"").replace(/[&<>\"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[ch]));
function fresh(){return{schema:5,selected:1,stage:0,completed:{},completedDates:{},stageDone:{},checks:{},notes:{},confidence:{},lastOpen:{},itemIndex:{},learnOrder:{},learnAttempts:{},itemRatings:{},retrieval:{},recallIndex:{},reviewQueue:[],resourceOpened:{},timerLeft:{},shiftEvents:[],legacySkips:0}}
function mergeState(raw){
  const base=fresh(),legacy=raw&&raw.schema!==5,s={...base,...raw};
  for(const k of ["completed","completedDates","stageDone","checks","notes","confidence","lastOpen","itemIndex","learnOrder","learnAttempts","itemRatings","retrieval","recallIndex","resourceOpened","timerLeft"])s[k]={...(raw?.[k]||{})};
  s.reviewQueue=Array.isArray(raw?.reviewQueue)?raw.reviewQueue:[];
  s.shiftEvents=Array.isArray(raw?.shiftEvents)?raw.shiftEvents:[];
  if(legacy){
    const map={0:0,1:2,2:3,3:1,4:4,5:5},mappedStages={},mappedChecks={};
    Object.entries(raw.stageDone||{}).forEach(([k,v])=>{const[day,stage]=k.split("-");mappedStages[`${day}-${map[stage]??stage}`]=v});
    Object.entries(raw.checks||{}).forEach(([k,v])=>{const[day,stage,...rest]=k.split("-");mappedChecks[`${day}-${map[stage]??stage}-${rest.join("-")}`]=v});
    s.stageDone=mappedStages;s.checks=mappedChecks;
    Object.entries(raw.lastOpen||{}).forEach(([day,stage])=>s.lastOpen[day]=map[stage]??stage);
    s.stage=map[raw.stage]??0;
    Object.entries(raw.vocabDone||{}).forEach(([day,items])=>{const pending=[];(COURSE[Number(day)-1]?.items||[]).forEach((_,i)=>{if(items[i])s.itemRatings[`${day}-${i}`]=1;else pending.push(i)});if(pending.length)s.learnOrder[day]=pending;else if((COURSE[Number(day)-1]?.items||[]).length)s.stageDone[`${day}-2`]=true});
    Object.entries(raw.recall||{}).forEach(([day,items])=>{Object.entries(items||{}).forEach(([i,rating])=>{s.itemRatings[`${day}-${i}`]=Math.max(s.itemRatings[`${day}-${i}`]??0,Number(rating));if(Number(rating)<2)s.reviewQueue.push({day:Number(day),index:Number(i),rating:Number(rating),due:Number(day)+1})})});
    s.migratedFrom=4;
  }
  s.schema=5;return s;
}
function load(){try{return mergeState(JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return fresh()}}
let state=load(),timer={left:60,running:false,id:null};
function firstOpen(){return COURSE.find(l=>!state.completed[l.day])||COURSE[COURSE.length-1]}
if(!state.shiftEvents.length&&Number(state.skips)>0){state.shiftEvents=[{fromDay:firstOpen().day,count:Number(state.skips),at:Date.now(),legacy:true}]}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function announce(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");t.setAttribute("role","status");clearTimeout(announce.id);announce.id=setTimeout(()=>t.classList.remove("show"),3200)}
function lesson(){return COURSE[state.selected-1]||COURSE[0]}
function stageKey(day,stage){return `${day}-${stage}`}
function checkKey(day,stage,item){return `${day}-${stage}-${item}`}
function itemKey(day,index){return `${day}-${index}`}
function stageIsDone(day,stage){return !!state.stageDone[stageKey(day,stage)]}
function getCheck(day,stage,item){return !!state.checks[checkKey(day,stage,item)]}
function setCheck(day,stage,item,value){state.checks[checkKey(day,stage,item)]=value;save()}
function effectiveDate(day){const d=new Date(START);let shift=0;state.shiftEvents.forEach(e=>{if(day>=e.fromDay)shift+=e.count||1});d.setDate(d.getDate()+day-1+shift);return d}
function fmt(d){return d.toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short",year:"numeric"})}
function resumeStage(day){if(state.completed[day])return 0;const saved=Number(state.lastOpen[day]);if(Number.isInteger(saved)&&saved>=0&&saved<6)return saved;for(let i=0;i<6;i++)if(!stageIsDone(day,i))return i;return 5}
function savedPosition(l){const s=resumeStage(l.day);if(s===2){const order=learnOrder(l),p=state.itemIndex[l.day]||0;return `${STAGES[s]}, sign ${Math.min(p+1,order.length)} of ${order.length}`}if(s===1){const prompts=retrievalPrompts(l),p=state.recallIndex[l.day]||0;return `${STAGES[s]}, prompt ${Math.min(p+1,prompts.length)} of ${prompts.length}`}return STAGES[s]}
function lessonPath(l){return["3–5 minute retrieval",`learn ${l.items.length} ${l.items.length===1?"item":"items"}`,"guided production drill","communication challenge","review and close"]}
function renderHome(){const n=firstOpen(),done=COURSE.filter(l=>state.completed[l.day]).length,position=savedPosition(n);$("homePhase").textContent=n.phase;$("homeTitle").textContent=n.title;$("homeFocus").textContent=n.purpose;$("homeDay").textContent=`Day ${n.day} of ${COURSE.length}`;$("homeDate").textContent=fmt(effectiveDate(n.day));$("homeTime").textContent=n.time;$("homeSaved").textContent=state.lastOpen[n.day]!==undefined?`Saved at ${position}`:"Not started";$("homeOutcome").textContent=n.mastery;$("todayPath").innerHTML=lessonPath(n).map(x=>`<li>${esc(x)}</li>`).join("");$("doneCount").textContent=done;$("remainCount").textContent=COURSE.length-done;$("progressBar").style.width=`${Math.round(done/COURSE.length*100)}%`;$("progressBar").parentElement.setAttribute("aria-label",`${done} of ${COURSE.length} lessons complete`);$("beginBtn").textContent=state.lastOpen[n.day]!==undefined?`Continue Day ${n.day}: ${position}`:`Start Day ${n.day}`;renderCourseMap();renderReviewSummary()}
function renderCourseMap(){const phases=[];COURSE.forEach(l=>{let p=phases.find(x=>x.name===l.phase);if(!p){p={name:l.phase,lessons:[]};phases.push(p)}p.lessons.push(l)});const current=firstOpen().day;$("journey").innerHTML=phases.map((p,pi)=>`<details class="phaseGroup" ${p.lessons.some(l=>l.day===current)||pi===0?"open":""}><summary><span>${esc(p.name)}</span><small>${p.lessons.filter(l=>state.completed[l.day]).length}/${p.lessons.length} complete</small></summary><div class="phaseDays">${p.lessons.map(l=>{const st=state.completed[l.day]?"Complete":l.day===current?(state.lastOpen[l.day]!==undefined?`Resume ${savedPosition(l)}`:"Next lesson"):"Available";return`<button class="day" data-day="${l.day}" type="button"><span class="dayNum">DAY ${l.day}</span><span><strong>${esc(l.title)}</strong><small>${esc(l.purpose)}</small></span><span class="status ${state.completed[l.day]?"complete":l.day===current?"current":""}">${esc(st)}</span></button>`}).join("")}</div></details>`).join("");document.querySelectorAll("[data-day]").forEach(b=>b.onclick=()=>openLesson(Number(b.dataset.day)))}
function renderReviewSummary(){const weak=state.reviewQueue.filter(q=>q.rating<2).slice(0,6);$("reviewSummary").innerHTML=weak.length?weak.map(q=>`<span class="reviewChip">${esc(COURSE[q.day-1]?.items[q.index]?.term||"Earlier item")}</span>`).join(""):"<span class=\"muted\">Your hesitant signs will appear here after practice.</span>"}
function openLesson(day){stopTimer();state.selected=day;state.stage=resumeStage(day);state.lastOpen[day]=state.stage;save();$("home").classList.add("hidden");$("session").classList.add("active");renderSession();window.scrollTo({top:0,behavior:"smooth"})}
function exitSession(){stopTimer();$("session").classList.remove("active");$("home").classList.remove("hidden");save();renderHome();window.scrollTo({top:0,behavior:"smooth"})}
function renderSession(){const l=lesson();$("sessionPhase").textContent=`${l.phase} · Day ${l.day} of ${COURSE.length} · ${fmt(effectiveDate(l.day))}`;$("sessionTitle").textContent=l.title;$("sessionFocus").textContent=l.purpose;renderRail();renderStage()}
function renderRail(){$("stageRail").innerHTML=STAGES.map((s,i)=>`<button type="button" class="stageDot ${i===state.stage?"active":stageIsDone(state.selected,i)?"done":""}" data-stage="${i}" ${i>state.stage&&!stageIsDone(state.selected,i-1)?"disabled":""} aria-current="${i===state.stage?"step":"false"}"><span>${i+1}</span>${s}</button>`).join("");document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>{state.stage=Number(b.dataset.stage);state.lastOpen[state.selected]=state.stage;save();renderSession();window.scrollTo({top:0,behavior:"smooth"})})}
function actionBox(action,why,ready){return`<section class="actionBox" aria-labelledby="do-now"><p class="eyebrow" id="do-now">DO THIS NOW</p><h3>${esc(action)}</h3><div class="reasonGrid"><div><strong>Why this matters</strong><p>${esc(why)}</p></div><div><strong>You are ready to continue when</strong><p>${esc(ready)}</p></div></div></section>`}
function checklist(items,stage){return`<div class="checklist">${items.map((x,i)=>`<label class="check ${getCheck(state.selected,stage,i)?"checked":""}"><input type="checkbox" data-check-item="${i}" ${getCheck(state.selected,stage,i)?"checked":""}><span>${esc(x)}</span></label>`).join("")}</div>`}
function helpBox(text){return`<details class="helpBox"><summary>I’m stuck</summary><p>${esc(text)}</p><button type="button" class="miniBtn" id="saveFromHelp">Save and return later</button></details>`}
function resourceCard(r,index){const opened=!!state.resourceOpened[`${state.selected}-${state.stage}-${index}`];return`<article class="resourceCard"><div><p class="eyebrow">${esc(r.source)}</p><h4>${esc(r.label)}</h4><p><strong>Why open it:</strong> ${esc(r.purpose)}</p><p><strong>Watch for:</strong> ${esc(r.watch)}</p></div><a class="resourceLink" data-resource="${index}" href="${esc(r.url)}" target="_blank" rel="noopener">${opened?"Reopen":"Open"} ${esc(r.label)} ↗</a>${opened?`<div class="returnCue"><strong>When you return</strong><p>${esc(r.returnCue)}</p></div>`:""}</article>`}
function nav(ready,message,last=false){return`<div class="stageNav"><div><button class="btn secondary" id="backStage" type="button" ${state.stage===0?"disabled":""}>Back</button><button class="btn ghost" id="saveExit" type="button">Save and leave</button></div><div>${last?`<button class="btn good" id="finishLesson" type="button" ${ready?"":"disabled"}>Finish Day ${state.selected}</button>`:`<button class="btn" id="nextStage" type="button" ${ready?"":"disabled"}>Continue to ${STAGES[state.stage+1]}</button>`}</div></div><p class="gateMessage" role="status">${esc(message)}</p>`}
function orientStage(l){const items=[`Read why today’s lesson matters: ${l.purpose}`,`Check the prerequisite: ${l.prior}`,"Place the device so your face, shoulders and hands remain visible"];const ready=items.every((_,i)=>getCheck(l.day,0,i));return`<div class="stageLabel">Step 1 of 6 · Orient</div>${actionBox("Read today’s purpose, then complete the three setup actions.","Orientation connects today to earlier learning and prevents practice becoming disconnected copying.",l.mastery)}<div class="orientationGrid"><div><p class="eyebrow">REAL-WORLD USE</p><p>${esc(l.use)}</p></div><div><p class="eyebrow">LANGUAGE & CULTURE</p><p>${esc(l.culture)}</p></div></div>${checklist(items,0)}<h4 class="sectionTitle">Open only what today needs</h4>${l.resources.map(resourceCard).join("")}${helpBox(l.stuck)}${nav(ready,ready?"Setup complete. Begin the short retrieval warm-up.":`Complete ${items.filter((_,i)=>!getCheck(l.day,0,i)).length} setup action(s).`)}`}
function retrievalPrompts(l){const due=state.reviewQueue.filter(q=>q.day<l.day&&q.rating<2).sort((a,b)=>(a.due||0)-(b.due||0)).slice(0,3).map(q=>({term:COURSE[q.day-1]?.items[q.index]?.term||"Earlier item",source:`Day ${q.day}`}));const prev=l.day>1?COURSE[l.day-2].items.slice(0,2).map(x=>({term:x.term,source:`Day ${l.day-1}`})):[];const foundation=l.day>4?[{term:l.day%2?"fingerspell your name":"hello",source:"Foundation"}]:[];const unique=[];[...due,...prev,...foundation].forEach(x=>{if(x.term&&!unique.some(y=>y.term===x.term))unique.push(x)});return(unique.length?unique:l.items.slice(0,3).map(x=>({term:x.term,source:"Today’s preview"}))).slice(0,6)}
function retrievalStage(l){const prompts=retrievalPrompts(l),idx=Math.min(state.recallIndex[l.day]||0,prompts.length-1),results=state.retrieval[l.day]||{},done=Object.keys(results).length>=prompts.length,p=prompts[idx];return`<div class="stageLabel">Step 2 of 6 · Retrieve</div>${actionBox(`Look at “${p.term}”. Wait five quiet seconds, then produce it before choosing a result.`,`Retrieval strengthens access to earlier learning. Forgetting gives the companion useful information; it is not failure.`,`You have honestly attempted all ${prompts.length} prompts. Correct answers are not required.`)}<div class="promptCard"><small>${esc(p.source)} · Prompt ${idx+1} of ${prompts.length}</small><strong>${esc(p.term)}</strong><button class="miniBtn" id="showRetrievalClue" type="button">Show one clue</button><p id="retrievalClue" hidden>Make only the starting handshape or first meaning block. If nothing returns, mark “Not remembered” and continue.</p></div><div class="ratingRow"><button class="btn good" data-retrieval="2">Remembered clearly</button><button class="btn warn" data-retrieval="1">Remembered with hesitation</button><button class="btn secondary" data-retrieval="0">Not remembered</button></div>${helpBox("Pause for five seconds. If nothing returns, show the clue, attempt only the first position, then record ‘Not remembered’. The item will return later.")}${nav(done,done?"Warm-up attempted. Weak items have been added to review.":`${Object.keys(results).length} of ${prompts.length} prompts attempted.`)}`}
function learnOrder(l){if(!Array.isArray(state.learnOrder[l.day])||!state.learnOrder[l.day].length)state.learnOrder[l.day]=l.items.map((_,i)=>i);return state.learnOrder[l.day]}
function learnStage(l){const order=learnOrder(l),pos=state.itemIndex[l.day]||0,finished=pos>=order.length,index=order[Math.min(pos,order.length-1)]??0,item=l.items[index],rating=state.itemRatings[itemKey(l.day,index)],opened=!!state.resourceOpened[`${l.day}-2-0`];if(finished)return`<div class="stageLabel">Step 3 of 6 · Learn</div>${actionBox("Review the learning results below, then continue.","Every item has moved through observe, copy, compare and recall. Items needing support are already queued.","Each item has an honest result recorded.")}<div class="summaryList">${l.items.map((x,i)=>`<div><strong>${esc(x.term)}</strong><span>${esc(RATINGS[state.itemRatings[itemKey(l.day,i)]]||"Attempted")}</span></div>`).join("")}</div>${helpBox(l.stuck)}${nav(true,"Learning cycle complete. Hesitant signs will return in a later warm-up.")}`;return`<div class="stageLabel">Step 3 of 6 · Learn</div>${actionBox(`Learn “${item.term}” using the ten-step cycle below.`,`Working with one item at a time removes decision fatigue and forces observation before imitation.`,`You have recalled the item with the example closed and chosen an honest result.`)}<div class="itemProgress"><span>Item ${pos+1} of ${order.length}</span><progress value="${pos}" max="${order.length}"></progress></div><ol class="microCycle"><li>Say the meaning to yourself.</li><li>Open the selected BSL example.</li><li>Watch once without moving.</li><li>Watch again: ${esc(l.observe)}</li><li>Copy slowly three times.</li><li>Compare handshape, location and movement.</li><li>Close the resource.</li><li>Wait five seconds and recall once.</li><li>Use it in today’s smallest possible phrase or context.</li><li>Choose the honest result below.</li></ol>${resourceCard(item.resource,0)}${opened?"":`<p class="gateMessage">Open the example before rating. Opening it is not proof of learning.</p>`}<div class="ratingRow"><button class="btn good" data-item-rating="2" ${opened?"":"disabled"}>Clear from memory</button><button class="btn warn" data-item-rating="1" ${opened?"":"disabled"}>Correct but hesitant</button><button class="btn secondary" data-item-rating="0" ${opened?"":"disabled"}>Needs another model</button></div>${helpBox(l.stuck)}${nav(false,`Complete the micro-cycle for “${item.term}”.`)}`}
function timerWidget(){return`<section class="timerBox"><div><p class="eyebrow">OPTIONAL ONE-MINUTE ROUND</p><strong id="timerReadout">1:00</strong><p>During the minute, repeat today’s drill calmly. When time ends, stop, rest your hands and complete the self-check.</p></div><div><button class="miniBtn" id="timerToggle" type="button">Start timer</button><button class="miniBtn" id="timerRestart" type="button">Restart</button></div></section>`}
function practiseStage(l){const items=[l.drill,`Focus on: ${l.observe}`,`Record one short attempt in the device camera, return here, and watch it once with sound muted. If you prefer not to record, use a mirror and complete the same visual check.`],ready=items.every((_,i)=>getCheck(l.day,3,i));return`<div class="stageLabel">Step 4 of 6 · Practise</div>${actionBox(l.drill,"A deliberate drill isolates today’s coordination before you use it in communication.",l.mastery)}${timerWidget()}${checklist(items,3)}<div class="reviewPanel"><p class="eyebrow">COMMON ERRORS TO CHECK</p><ul>${l.errors.map(x=>`<li>${esc(x)}</li>`).join("")}</ul></div>${helpBox(l.stuck)}${nav(ready,ready?"Practice evidence complete.":`Complete ${items.filter((_,i)=>!getCheck(l.day,3,i)).length} practice action(s).`)}`}
function useStage(l){const items=[`Receptive check: ${l.receptive}`,`Communication challenge: ${l.use}`,`Self-review: ${l.review}`],ready=items.every((_,i)=>getCheck(l.day,4,i));return`<div class="stageLabel">Step 5 of 6 · Use</div>${actionBox(l.use,"Communication combines vocabulary, visual grammar, watching and repair. It is the purpose of the separate drills.",l.mastery)}${checklist(items,4)}<div class="schoolBox"><p class="eyebrow">USE THIS IN SCHOOL — OPTIONAL</p><p>${esc(l.school)}</p><small>Remain clear that you are a learner. Continue through Deaf-led teaching and real interaction.</small></div>${helpBox(l.stuck)}${nav(ready,ready?"You completed the communication attempt and review.":`Complete ${items.filter((_,i)=>!getCheck(l.day,4,i)).length} evidence action(s). Success is not required—an honest attempt is.`)}`}
function closeStage(l){const note=(state.notes[l.day]||""),conf=state.confidence[l.day],ready=note.trim().length>=20&&!!conf;return`<div class="stageLabel">Step 6 of 6 · Close</div>${actionBox("Read the mastery statement, make an honest decision, then write one next action.","A precise close turns today’s performance into tomorrow’s retrieval rather than a vague feeling of completion.",l.mastery)}<div class="masteryBox"><p class="eyebrow">TODAY’S MASTERY DECISION</p><p>${esc(l.mastery)}</p><p><strong>Reflection:</strong> ${esc(l.reflect)}</p></div><label class="fieldLabel" for="notes">Write what was clear and what should return</label><textarea id="notes" placeholder="Clear today…\nBring back tomorrow…">${esc(note)}</textarea><div class="confidence"><button data-confidence="1" class="${conf===1?"active":""}">Needs support</button><button data-confidence="2" class="${conf===2?"active":""}">Hesitant but usable</button><button data-confidence="3" class="${conf===3?"active":""}">Clear today</button></div><div class="previewBox"><p class="eyebrow">NEXT LESSON</p><p>${esc(l.preview)}</p></div>${helpBox(l.stuck)}${nav(ready,ready?"Reflection saved. You can finish the lesson.":"Write at least 20 characters and choose one confidence level.",true)}`}
function renderStage(){stopTimer();const l=lesson();let html=[orientStage,retrievalStage,learnStage,practiseStage,useStage,closeStage][state.stage](l);$("stageCard").innerHTML=html;bindStage(l)}
function stageReady(l,stage){if(stage===0)return[0,1,2].every(i=>getCheck(l.day,0,i));if(stage===1)return Object.keys(state.retrieval[l.day]||{}).length>=retrievalPrompts(l).length;if(stage===2)return(state.itemIndex[l.day]||0)>=learnOrder(l).length;if(stage===3||stage===4)return[0,1,2].every(i=>getCheck(l.day,stage,i));if(stage===5)return(state.notes[l.day]||"").trim().length>=20&&!!state.confidence[l.day];return false}
function enqueue(day,index,rating,due){const existing=state.reviewQueue.find(q=>q.day===day&&q.index===index);if(existing){existing.rating=rating;existing.due=due}else state.reviewQueue.push({day,index,rating,due})}
function bindStage(l){document.querySelectorAll("[data-check-item]").forEach(c=>c.onchange=()=>{setCheck(l.day,state.stage,Number(c.dataset.checkItem),c.checked);renderStage()});document.querySelectorAll("[data-resource]").forEach(a=>a.onclick=()=>{state.resourceOpened[`${l.day}-${state.stage}-${a.dataset.resource}`]=true;save();setTimeout(renderStage,250)});const saveHelp=$("saveFromHelp");if(saveHelp)saveHelp.onclick=exitSession;const back=$("backStage");if(back)back.onclick=()=>moveStage(-1);const saveExit=$("saveExit");if(saveExit)saveExit.onclick=exitSession;const next=$("nextStage");if(next)next.onclick=()=>{if(!stageReady(l,state.stage)){announce("Complete the visible attempt before continuing.");return}state.stageDone[stageKey(l.day,state.stage)]=true;moveStage(1)};
document.querySelectorAll("[data-retrieval]").forEach(b=>b.onclick=()=>{const prompts=retrievalPrompts(l),idx=state.recallIndex[l.day]||0,rating=Number(b.dataset.retrieval);state.retrieval[l.day]=state.retrieval[l.day]||{};state.retrieval[l.day][idx]=rating;const source=prompts[idx];const sourceDay=Number((source.source.match(/\d+/)||[])[0]);if(sourceDay){const itemIndex=COURSE[sourceDay-1].items.findIndex(x=>x.term===source.term);if(itemIndex>=0)enqueue(sourceDay,itemIndex,rating,l.day+(rating===0?1:rating===1?2:7))}state.recallIndex[l.day]=Math.min(idx+1,prompts.length-1);save();renderStage()});const clue=$("showRetrievalClue");if(clue)clue.onclick=()=>{$("retrievalClue").hidden=false;clue.disabled=true};
document.querySelectorAll("[data-item-rating]").forEach(b=>b.onclick=()=>{const order=learnOrder(l),pos=state.itemIndex[l.day]||0,index=order[pos],rating=Number(b.dataset.itemRating),k=itemKey(l.day,index);state.itemRatings[k]=rating;state.learnAttempts[k]=(state.learnAttempts[k]||0)+1;enqueue(l.day,index,rating,l.day+(rating===0?1:rating===1?2:7));if(rating===0&&state.learnAttempts[k]<2)order.push(index);state.itemIndex[l.day]=pos+1;delete state.resourceOpened[`${l.day}-2-0`];save();renderStage()});
const notes=$("notes");if(notes)notes.oninput=e=>{state.notes[l.day]=e.target.value;save();const ready=stageReady(l,5),finish=$("finishLesson"),message=document.querySelector(".gateMessage");if(finish)finish.disabled=!ready;if(message)message.textContent=ready?"Reflection saved. You can finish the lesson.":"Write at least 20 characters and choose one confidence level."};document.querySelectorAll("[data-confidence]").forEach(b=>b.onclick=()=>{state.confidence[l.day]=Number(b.dataset.confidence);save();renderStage()});const finish=$("finishLesson");if(finish)finish.onclick=()=>{if(!stageReady(l,5))return;state.stageDone[stageKey(l.day,5)]=true;state.completed[l.day]=true;state.completedDates[l.day]=new Date().toISOString();delete state.lastOpen[l.day];save();announce(`Day ${l.day} complete. Your next retrieval is ready.`);setTimeout(exitSession,700)};bindTimer()}
function moveStage(delta){stopTimer();state.stage=Math.max(0,Math.min(5,state.stage+delta));state.lastOpen[state.selected]=state.stage;save();renderSession();window.scrollTo({top:0,behavior:"smooth"})}
function bindTimer(){const toggle=$("timerToggle"),restart=$("timerRestart"),day=state.selected;if(!toggle)return;timer.left=Number.isFinite(state.timerLeft[day])?state.timerLeft[day]:60;updateTimer();toggle.onclick=()=>{timer.running=!timer.running;toggle.textContent=timer.running?"Pause timer":"Resume timer";if(timer.running)timer.id=setInterval(()=>{timer.left--;state.timerLeft[day]=timer.left;save();updateTimer();if(timer.left<=0){delete state.timerLeft[day];save();stopTimer();announce("Round complete. Rest your hands, then complete the self-check.")}},1000)};restart.onclick=()=>{stopTimer();timer.left=60;state.timerLeft[day]=60;save();updateTimer()}}
function updateTimer(){const r=$("timerReadout");if(r)r.textContent=`${Math.floor(timer.left/60)}:${String(timer.left%60).padStart(2,"0")}`}
function stopTimer(){if(timer.id)clearInterval(timer.id);timer.id=null;timer.running=false}
function moveTodayForward(){const fromDay=firstOpen().day;if(!confirm(`Move Day ${fromDay} and every unfinished lesson forward by one day? Completed lesson dates will not change.`))return;state.shiftEvents.push({fromDay,count:1,at:Date.now()});save();renderHome();$("undoShift").hidden=false;announce("Unfinished lessons moved forward by one day. Undo is available below.")}
function undoShift(){if(!state.shiftEvents.length)return;state.shiftEvents.pop();save();renderHome();announce("The date shift was undone.")}
$("beginBtn").onclick=()=>openLesson(firstOpen().day);$("exitBtn").onclick=exitSession;$("printBtn").onclick=()=>window.print();$("moveDayBtn").onclick=moveTodayForward;$("undoShift").onclick=undoShift;$("resetBtn").onclick=()=>{if(confirm("Reset all BSL progress, notes and review history on this device? This cannot be undone.")){localStorage.removeItem(KEY);state=fresh();renderHome();announce("Progress reset")}};window.addEventListener("beforeunload",save);save();renderHome();
