const STAGES=["Prepare","Watch","Practise","Recall","Use","Finish"];
const LABELS={1:"Needs another pass",2:"Growing",3:"Usable today"};
function fresh(){return{selected:1,stage:0,completed:{},stageDone:{},vocabDone:{},checks:{},recall:{},notes:{},confidence:{},skips:0,lastOpen:{}}}
function load(){try{return Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return fresh()}}
let state=load(),recallIndex=0;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
function lesson(){return COURSE.find(x=>x.day===state.selected)||COURSE[0]}
function firstOpen(){return COURSE.find(x=>!state.completed[x.day])||COURSE[COURSE.length-1]}
function effectiveDate(day){const d=new Date(START);d.setDate(d.getDate()+day-1+(state.skips||0));return d}
function fmt(d){return d.toLocaleDateString("en-AU",{weekday:"short",day:"numeric",month:"short",year:"numeric"})}
function slug(s){return s.toLowerCase().replace(/[^a-z0-9 ]/g,"").trim().replace(/\s+/g,"-")}
function signLink(s){return "https://www.signbsl.com/sign/"+slug(s)}
function stageKey(day,stage){return `${day}-${stage}`}
function checkedKey(day,stage,item){return `${day}-${stage}-${item}`}
function stageIsDone(day,stage){return !!state.stageDone[stageKey(day,stage)]}
function setCheck(day,stage,item,value){state.checks[checkedKey(day,stage,item)]=value;save()}
function getCheck(day,stage,item){return !!state.checks[checkedKey(day,stage,item)]}
function stageChecksDone(day,stage,count){for(let i=0;i<count;i++)if(!getCheck(day,stage,i))return false;return true}
function resumeStage(day){if(state.completed[day])return 0;const saved=state.lastOpen?.[day];if(Number.isInteger(saved))return Math.max(0,Math.min(5,saved));for(let i=0;i<6;i++)if(!stageIsDone(day,i))return i;return 5}
function trustedLinks(l){const links=[["Search the BSL dictionary","https://www.signbsl.com/"],["Signature learner support","https://www.signature.org.uk/students/learning-support/"]];if(l.title.toLowerCase().includes("finger"))links.unshift(["Open the fingerspelling guide","https://www.signature.org.uk/students/learning-support/fingerspelling/"]);return links.slice(0,3)}
function renderHome(){const n=firstOpen(),done=COURSE.filter(l=>state.completed[l.day]).length;$("homePhase").textContent=n.phase;$("homeTitle").textContent=n.title;$("homeFocus").textContent=n.focus;$("homeDay").textContent=`Day ${n.day} of ${COURSE.length}`;$("homeDate").textContent=fmt(effectiveDate(n.day));$("doneCount").textContent=done;$("remainCount").textContent=COURSE.length-done;$("stageCount").textContent=Object.values(state.stageDone).filter(Boolean).length;const last=Object.keys(state.confidence).sort((a,b)=>a-b).pop();$("confidenceText").textContent=last?LABELS[state.confidence[last]]:"—";$("progressBar").style.width=Math.round(done/COURSE.length*100)+"%";$("beginBtn").textContent=state.lastOpen?.[n.day]>0?`Resume at ${STAGES[resumeStage(n.day)]}`:"Begin guided lesson";$("journey").innerHTML=COURSE.map(l=>{const current=l.day===n.day&&!state.completed[l.day],resume=resumeStage(l.day);return `<button class="day" data-day="${l.day}" type="button"><div class="dayNum">DAY ${l.day}</div><div><h4>${l.title}</h4><p>${l.phase} · ${l.focus}</p></div><span class="status ${state.completed[l.day]?"complete":current?"current":""}">${state.completed[l.day]?"Complete":current&&resume?`Resume ${resume+1}/6`:current?"Next":"Open"}</span></button>`}).join("");document.querySelectorAll("[data-day]").forEach(el=>el.onclick=()=>openLesson(Number(el.dataset.day)))}
function openLesson(day){state.selected=day;state.stage=resumeStage(day);state.lastOpen[day]=state.stage;save();$("home").classList.add("hidden");$("session").classList.add("active");renderSession();window.scrollTo({top:0,behavior:"smooth"})}
function renderRail(){const done=STAGES.filter((_,i)=>stageIsDone(state.selected,i)).length;$("stageRail").innerHTML=STAGES.map((s,i)=>`<button type="button" class="stageDot ${i===state.stage?"active":stageIsDone(state.selected,i)?"done":""}" data-stage="${i}" ${i>done&&!stageIsDone(state.selected,i)?"disabled":""}>${i+1} · ${s}</button>`).join("");document.querySelectorAll("[data-stage]").forEach(b=>b.onclick=()=>{state.stage=Number(b.dataset.stage);state.lastOpen[state.selected]=state.stage;save();renderSession();window.scrollTo({top:0,behavior:"smooth"})})}
function checklist(items,stage){return `<div class="checklist">${items.map((x,i)=>`<label class="check ${getCheck(state.selected,stage,i)?"checked":""}"><input type="checkbox" data-check-item="${i}" ${getCheck(state.selected,stage,i)?"checked":""}><span>${x}</span></label>`).join("")}</div>`}
function vocabCards(l){return l.vocab.map((v,i)=>{const done=!!state.vocabDone[l.day]?.[i];return `<article class="vocabCard ${done?"done":""}"><div class="stepFlag">${done?"DONE":"NEXT"}</div><h4>${v}</h4><ol class="micro"><li>Open the video.</li><li>Watch twice without moving.</li><li>Copy slowly three times.</li><li>Close it and produce once from memory.</li></ol><div class="resourceRow"><a class="resourceLink" href="${signLink(v)}" target="_blank" rel="noopener">Watch ${v} ↗</a><button class="miniBtn ${done?"done":""}" data-vocab="${i}" type="button">${done?"Practised ✓":"I completed all 4 steps"}</button></div></article>`}).join("")}
function helpBox(text){return `<details class="helpBox"><summary>I am stuck</summary><p>${text}</p></details>`}
function nextButton(label="Complete this stage and continue"){return `<button class="btn" id="nextStage" type="button">${label}</button>`}
function renderStage(){const l=lesson(),i=state.stage,card=$("stageCard");let body="",requirements=0;
if(i===0){const items=["Place the screen where both hands and your face are visible.","Open your camera or a mirror for self-checking.","Read the final challenge below and say to yourself what success will look like."];requirements=items.length;body=`<div class="stageLabel">Step 1 of 6 · Prepare</div><h3>Set up, then begin</h3><p class="lead">You are learning <strong>${l.focus.toLowerCase()}</strong>. This lesson will tell you exactly what to do, in order.</p><div class="nowBox"><span>DO THIS NOW</span><strong>Complete the three preparation actions below.</strong></div>${checklist(items,i)}<div class="prompt"><div><small>Your finish line</small>${l.challenge}</div></div>${helpBox("You do not need special equipment. A phone or tablet camera is enough. Keep the session small and clear rather than perfect.")}`}
if(i===1){requirements=l.vocab.length;const done=Object.values(state.vocabDone[l.day]||{}).filter(Boolean).length;body=`<div class="stageLabel">Step 2 of 6 · Watch</div><h3>Learn one item at a time</h3><p class="lead">Do not browse the whole internet. Work down these cards in order. The stage unlocks when every item has been watched, copied and recalled once.</p><div class="nowBox"><span>YOUR POSITION</span><strong>${done} of ${l.vocab.length} items completed</strong></div><div class="resourceRow">${trustedLinks(l).map(x=>`<a class="resourceLink" href="${x[1]}" target="_blank" rel="noopener">${x[0]} ↗</a>`).join("")}</div><div class="vocabGrid">${vocabCards(l)}</div>${helpBox("If a direct sign page is unavailable, use the dictionary search button and type the exact word. BSL has regional variants. Choose one clear variant for today and stay consistent.")}`}
if(i===2){const items=[...l.steps,"Record one short practice round and watch it back without sound."];requirements=items.length;body=`<div class="stageLabel">Step 3 of 6 · Practise</div><h3>Follow the practice rounds</h3><p class="lead">Work from the first box to the last. Tick a box only after doing it, not before.</p><div class="nowBox"><span>COACHING RULE</span><strong>Accuracy first. Smoothness second. Speed last.</strong></div>${checklist(items,i)}<div class="prompt"><div><small>Keep in mind</small>${l.coach}</div></div>${helpBox("When a movement feels awkward, reduce the speed and range. Compare handshape, orientation, location, movement and facial expression separately.")}`}
if(i===3){const scores=state.recall[l.day]||{},passed=Object.values(scores).filter(v=>v===2).length,needed=Math.max(3,Math.ceil(l.vocab.length*.7)),word=l.vocab[recallIndex%l.vocab.length];body=`<div class="stageLabel">Step 4 of 6 · Recall</div><h3>Prove what you can retrieve</h3><p class="lead">Look at the prompt, sign it without opening a resource, then mark the result honestly.</p><div class="nowBox"><span>CURRENT PROMPT ${recallIndex+1} OF ${l.vocab.length}</span><strong>${word}</strong></div><div class="recallActions"><button class="btn good" data-result="2" type="button">I produced it clearly</button><button class="btn warn" data-result="1" type="button">Hesitant / partly right</button><button class="btn secondary" data-result="0" type="button">I could not recall it</button></div><div class="instruction"><strong>Pass target:</strong> ${passed} clear of ${needed} needed. Hesitant items do not count yet. After choosing, the next prompt appears automatically.</div><div class="resourceRow"><button class="miniBtn" id="restartRecall" type="button">Restart prompts</button><button class="miniBtn" id="reviewWeak" type="button">Show items to revisit</button></div><div id="weakList" class="instruction" hidden>${l.vocab.filter((_,x)=>scores[x]!==2).join(" · ")||"None. You met the clear-recall target."}</div>${helpBox("Pause for five seconds before marking an item as forgotten. If it is still missing, mark it honestly, reopen that sign during a short revisit, then restart the prompts.")}`}
if(i===4){const items=["Complete the challenge once using notes.","Repeat with fewer prompts and clearer facial expression.","Record one final version without voice.","Watch it back and identify one specific improvement.","Repeat the improved version once."];requirements=items.length;body=`<div class="stageLabel">Step 5 of 6 · Use</div><h3>Communicate something real</h3><p class="lead">This is the point of the lesson. You are moving from separate signs into a message.</p><div class="prompt"><div><small>Your practical challenge</small>${l.challenge}</div></div><div class="nowBox"><span>START HERE</span><strong>Do the first attempt slowly with notes. Then work downward.</strong></div>${checklist(items,i)}${helpBox("Make the message smaller rather than abandoning it. Use two or three clear signs, natural gaze and facial expression, then build it back up.")}`}
if(i===5){body=`<div class="stageLabel">Step 6 of 6 · Finish</div><h3>Make tomorrow easier</h3><p class="lead">${l.reflect}</p><label class="fieldLabel" for="notes">Write two short sentences</label><textarea id="notes" placeholder="1. I can now…\n2. Tomorrow I will revisit…"></textarea><h4>Choose the most honest confidence level</h4><div class="confidence"><button data-confidence="1" type="button">Needs another pass</button><button data-confidence="2" type="button">Growing</button><button data-confidence="3" type="button">Usable today</button></div><div class="instruction"><strong>Before finishing:</strong> your reflection must contain at least 12 characters and you must choose one confidence level.</div>${helpBox("Choose ‘Needs another pass’ freely. It does not fail the lesson. It simply tells the companion where the learning edge is.")}`}
const ready=stageReady(l,i,requirements);body+=`<div class="stageNav"><div><button class="btn secondary" id="backStage" type="button" ${i===0?"disabled":""}>Previous step</button><button class="btn ghost" id="saveExit" type="button">Save and leave</button></div><div>${i<5?nextButton():`<button class="btn warn" id="skipLesson" type="button">I cannot study today</button><button class="btn good" id="finishLesson" type="button">Finish lesson</button>`}</div></div><p class="gateMessage" id="gateMessage">${ready?"Ready to continue.":gateMessage(l,i,requirements)}</p>`;card.innerHTML=body;
bindStage(l,i,requirements)}
function stageReady(l,i,count){if(i===1)return l.vocab.every((_,x)=>!!state.vocabDone[l.day]?.[x]);if(i===3){const pass=Math.max(3,Math.ceil(l.vocab.length*.7));return Object.values(state.recall[l.day]||{}).filter(v=>v===2).length>=pass}if(i===5)return (state.notes[l.day]||"").trim().length>=12&&!!state.confidence[l.day];return stageChecksDone(l.day,i,count)}
function gateMessage(l,i,count){if(i===1)return "Complete every vocabulary card before continuing.";if(i===3)return "Reach the clear-recall target before continuing.";if(i===5)return "Add two short reflection sentences and select confidence.";const done=Array.from({length:count},(_,x)=>getCheck(l.day,i,x)).filter(Boolean).length;return `Complete ${count-done} more action${count-done===1?"":"s"} before continuing.`}
function bindStage(l,i,requirements){document.querySelectorAll("[data-check-item]").forEach(c=>c.onchange=()=>{setCheck(l.day,i,Number(c.dataset.checkItem),c.checked);renderStage()});document.querySelectorAll("[data-vocab]").forEach(b=>b.onclick=()=>{state.vocabDone[l.day]=state.vocabDone[l.day]||{};state.vocabDone[l.day][Number(b.dataset.vocab)]=!state.vocabDone[l.day][Number(b.dataset.vocab)];save();renderStage()});
if(i===3){document.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>{state.recall[l.day]=state.recall[l.day]||{};state.recall[l.day][recallIndex]=Number(b.dataset.result);recallIndex=(recallIndex+1)%l.vocab.length;save();renderStage()});$("restartRecall").onclick=()=>{recallIndex=0;renderStage()};$("reviewWeak").onclick=()=>{$("weakList").hidden=!$("weakList").hidden}}
if(i===5){$("notes").value=state.notes[l.day]||"";$("notes").oninput=e=>{state.notes[l.day]=e.target.value;save();$("gateMessage").textContent=gateMessage(l,i,requirements)};document.querySelectorAll("[data-confidence]").forEach(b=>{b.classList.toggle("active",Number(b.dataset.confidence)===state.confidence[l.day]);b.onclick=()=>{state.confidence[l.day]=Number(b.dataset.confidence);save();renderStage()}})}
$("backStage").onclick=()=>moveStage(-1);$("saveExit").onclick=exitSession;
if(i<5)$("nextStage").onclick=()=>{if(!stageReady(l,i,requirements)){toast(gateMessage(l,i,requirements));return}state.stageDone[stageKey(l.day,i)]=true;moveStage(1)};
if(i===5){$("finishLesson").onclick=()=>{if(!stageReady(l,i,requirements)){toast(gateMessage(l,i,requirements));return}state.stageDone[stageKey(l.day,i)]=true;state.completed[l.day]=true;delete state.lastOpen[l.day];save();toast("Lesson complete. Your place is saved.");setTimeout(exitSession,550)};$("skipLesson").onclick=()=>{if(confirm("Shift every unfinished lesson forward by one day? Your progress will remain saved.")){state.skips=(state.skips||0)+1;save();toast("Course shifted forward by one day");exitSession()}}}}
function moveStage(delta){state.stage=Math.max(0,Math.min(5,state.stage+delta));state.lastOpen[state.selected]=state.stage;save();renderSession();window.scrollTo({top:0,behavior:"smooth"})}
function renderSession(){const l=lesson();$("sessionPhase").textContent=`${l.phase} · Day ${l.day} of ${COURSE.length} · ${fmt(effectiveDate(l.day))}`;$("sessionTitle").textContent=l.title;$("sessionFocus").textContent=l.focus;renderRail();renderStage()}
function exitSession(){$("session").classList.remove("active");$("home").classList.remove("hidden");save();renderHome();window.scrollTo({top:0,behavior:"smooth"})}
$("beginBtn").onclick=()=>openLesson(firstOpen().day);$("exitBtn").onclick=exitSession;$("printBtn").onclick=()=>window.print();$("resetBtn").onclick=()=>{if(confirm("Reset all saved progress on this device? This cannot be undone.")){localStorage.removeItem(KEY);state=fresh();renderHome();toast("Progress reset")}};
window.addEventListener("beforeunload",save);renderHome();
